# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
services:
  api-gateway:
    image: krakend
    ports:
      - 8080:8080
    volumes:
      - ./krakend:/etc/krakend/

  auth:
    build:
      context: ./auth
    ports:
      - 3000:3000

  chatbot-api:
    build:
      context: ./chatbot-api
    env_file:
      - ./chatbot-api/.env
    ports:
      - 8000:8000
    depends_on:
      - db

  chatbot-evaluate-api:
    build:
      context: ./chatbot-evaluate/api
    env_file:
      - ./chatbot-evaluate/api/.env
    ports:
      - 8002:8000
    depends_on:
      - queue
      - db

  # chatbot-evaluate-worker:
  #   build:
  #     context: ./chatbot-evaluate/worker
  #   # env_file:
  #   #   - ./chatbot-evaluate/worker/.env
  #   depends_on:
  #     - queue

  chatbot-index-api:
    build:
      context: ./chatbot-index/api
    env_file:
      - ./chatbot-index/api/.env
    ports:
      - 8003:8000
    depends_on:
      - queue

  # chatbot-index-worker:
  #   build:
  #     context: ./chatbot-index/worker
  #   # env_file:
  #   #   - ./chatbot-index/worker/.env
  #   depends_on:
  #     - queue

  frontend:
    build:
      context: ./frontend
    # env_file:
    #   - ./frontend/.env
    ports:
      - 80:80

  db:
    image: postgres:17
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    volumes:
      - ./db/data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - 5432:5432

  storage:
    image: minio/minio:latest
    volumes:
      - ./minio/:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    env_file:
      - .minio.env

  vector-db:
    image: redis/redis-stack:7.4.0-v8
    ports:
      - 6379:6379
      - 8001:8001
    volumes:
      - ./vector-db/data:/data

  queue:
    image: redis:8.4
    ports:
      - 6380:6379
    volumes:
      - ./queue/data:/data
    command: ["redis-server", "--appendonly", "yes"]
