# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker Compose reference guide at
# https://docs.docker.com/go/compose-spec-reference/

# Here the instructions define your application as a service called "server".
# This service is built from the Dockerfile in the current directory.
# You can add other services your application may depend on here, such as a
# database or a cache. For examples, see the Awesome Compose repository:
# https://github.com/docker/awesome-compose
services:
  api-gateway:
    image: krakend
    ports:
      - 8080:8080
    volumes:
      - ./krakend:/etc/krakend/

  auth:
    build:
      context: .
      dockerfile: ./auth/Dockerfile
    ports:
      - 3000:3000

  chatbot-api:
    build:
      context: .
      dockerfile: ./chatbot-api/Dockerfile
    env_file:
      - ./chatbot-api/.env
    ports:
      - 8000:8000
    depends_on:
      - db

  chatbot-evaluate-api:
    build:
      context: .
      dockerfile: ./chatbot-evaluate/api/Dockerfile
    env_file:
      - ./chatbot-evaluate/api/.env
    ports:
      - 8002:8000
    depends_on:
      - queue
      - db
      - vector-db

  # chatbot-evaluate-worker:
  #   build:
  #     context: ./chatbot-evaluate/worker
  #   # env_file:
  #   #   - ./chatbot-evaluate/worker/.env
  #   depends_on:
  #     - queue

  chatbot-index-api:
    build:
      context: .
      dockerfile: ./chatbot-index/api/Dockerfile
    env_file:
      - ./chatbot-index/api/.env
    ports:
      - 8003:8000
    depends_on:
      - queue
      - storage

  # chatbot-index-worker:
  #   build:
  #     context: ./chatbot-index/worker
  #   # env_file:
  #   #   - ./chatbot-index/worker/.env
  #   depends_on:
  #     - queue

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - 80:80

  db:
    image: postgres:17
    restart: always
    shm_size: 128mb
    volumes:
      - ./db/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db
    ports:
      - 5432:5432

  storage:
    image: minio/minio:latest
    volumes:
      - ./minio/:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=minioadmin

  vector-db:
    image: redis/redis-stack:7.4.0-v8
    ports:
      - 6379:6379
      - 8001:8001
    volumes:
      - ./vector-db/data:/data

  queue:
    image: redis:8.4
    ports:
      - 6380:6379
    volumes:
      - ./queue/data:/data
    command: ["redis-server", "--appendonly", "yes"]

  langfuse-worker:
    image: docker.io/langfuse/langfuse-worker:3.115
    ports:
      - 3030:3030
    env_file:
      - ./.langfuse.env
    depends_on:
      - db
      - storage
      - valkey
      - clickhouse

  langfuse-web:
    image: docker.io/langfuse/langfuse:3.115
    ports:
      - 4001:3000
    env_file:
      - ./.langfuse.env
    depends_on:
      - langfuse-worker

  clickhouse:
    image: docker.io/clickhouse/clickhouse-server:25.8.8.26-alpine
    user: "101:101"
    environment:
      CLICKHOUSE_DB: default
      CLICKHOUSE_USER: clickhouse
      CLICKHOUSE_PASSWORD: clickhouse
    volumes:
      - langfuse_clickhouse_data:/var/lib/clickhouse
      - langfuse_clickhouse_logs:/var/log/clickhouse-server
    ports:
      - 8123:8123
      - 9002:9000

  valkey:
    image: valkey/valkey:8.1.4-alpine3.22

volumes:
  langfuse_clickhouse_data:
    driver: local
  langfuse_clickhouse_logs:
    driver: local
