[project]
name = "dos-utility"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Luca Scopelliti BID", email = "luca.scopelliti@bidcompany.it" }
]
requires-python = ">=3.13"
dependencies = [
    "boto3>=1.42.28",
    "pydantic-settings>=2.12.0",
]

[project.scripts]
dos-utility = "dos_utility:main"

[build-system]
requires = ["uv_build>=0.9.18,<0.10.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.0.2",
    "pytest-cov>=7.0.0",
]
